Template1
dib-lab/training-by-practice pull request #4
Opened 2017-01-12 02:48 UTC by ADahlgren

Initial solutions to problems 6 and 7.

2017-01-12 16:20 UTC, drtamermansour requested changes

2017-01-12 16:20 UTC, drtamermansour commented on main.sh
> +sed 's/chr//' hg19.coding_subset.bed > hg19.coding_subset.ensFormat.bed
This would remove the word "chr" anywhere in the file. We need something more careful

2017-01-12 16:20 UTC, drtamermansour commented on main.sh
> +awk '$4 ~ /EnsCodingFull/' hg19.coding_subset.bed > hg19.coding_subset.EnsCodingFull.bed
Good Job

2017-01-12 21:37 UTC, ADahlgren commented
I mean problem 6...

2017-01-13 16:04 UTC, drtamermansour approved these changes

2017-01-13 16:04 UTC, merged